
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initial‐size: 5
    min‐idle: 5
    max‐active: 20
    max‐wait: 60000
    time‐between‐eviction‐runs‐millis: 60000
    min‐evictable‐idle‐time‐millis: 300000
    validation‐query: SELECT 1 FROM DUAL
    test‐while‐idle: true
    test‐on‐borrow: true
    test‐on‐return: false
    pool‐prepared‐statements: true
    max‐pool‐prepared‐statement‐per‐connection‐size: 20
    filter:
      stat:
        slow‐sql‐millis: 1
        log‐slow‐sql: true
  redis:
    host: 47.113.185.139
    port: 6379
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期
#      key-prefix: 'click:' #前缀

# mp日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志到控制台


#debug: true
